Q1. 본격적으로 Numpy와 친해지기 위해서 다양한 연산을 연습해볼 예정입니다. 무작위의 데이터를 가 진 5x3의 행렬을 가지는 numpy array와 3x2 행렬을 가지는 numpy array를 만든 후 행열곱 연산을 진행해보세요.

In [26]:
import numpy as np

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot = np.dot(arr1, arr2)
print(dot)


[[1.0522388  1.13008462]
 [0.94647301 1.12266253]
 [0.25155845 0.16943393]
 [0.83935462 0.97323523]
 [0.38166399 0.40910348]]


Q2. 두번째로는 numpy에서 자주 사용하는 concatenate 연산에 대한 미션을 수행해보겠습니다. 이제 Numpy에서 사용하는 2개의 numpy array가 있을때, 두 numpy array의 concatenate 연산을 구해보세요.  

- axis는 0, 1 두개로 연산한 결과를 출력해보세요.
- 각 데이터가 어떤 형태로 더해지는지 확인해보세요.

In [27]:
arr1 = np.array([[5,7],[9,11]], float)
arr2 = np.array([[2,4],[6,8]], float)

concat_1 = np.concatenate((arr1, arr2), axis = 0)
concat_2 = np.concatenate((arr1, arr2), axis = 1)

print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]
[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


Q3. 3번부터 5번까지의 미션는 Numpy를 이용해서 정답값을 예측해보는 linear regression을 구현해 보는 미션입니다. 첫번째 단계로 데이터를 준비해보도록 하겠습니다. 아래와 같이 데이터가 주어져있을 때, 경사하강법을 위한 데이터를 분리해보세요.

- 주어진 xy 데이터를 이용해서 학습과 정답 데이터를 준비해보세요.
- *추가 수정* 문제에서 주어진 xy에서 대괄호를 한 번 더 묶어주어야 문제 해결이 가능합니다.
(차원 관련)  (np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])

In [28]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
               [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)  


[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


Q4. 경사 하강법 구현을 위해서 위에서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의해보세요. 여기서 구현한 weight와 bias 는 linear regression 계산을 진행할시 직선의 기울기와 y 절편의 값이 됩니다.

- numpy 내의 random 함수를 이용해보세요.

In [29]:
beta_gd = np.random.rand(1,)
bias = np.random.rand(1,)

print(beta_gd, bias)

[0.46700427] [0.86359876]


Q5. 이제 최종적으로 linear regression을 경사하강법으로 학습하는 코드를 구현해봅시다. 경사하강법 구현을 위한 학습 Loop를 구현해보세요. 최종적으로 1000회 반복했을 시에 결과를 출력하세요.

- 단, Error는 차이의 제곱을 이용해서 계산해주세요.
- Gradient 값은 우리가 예측하는 각 변수에 대한 미분값입니다.

In [38]:
import numpy as np
from math import sqrt


xy = np.array([[1., 2., 3., 4., 5., 6.],
               [3., 6., 9., 12., 15., 18.]])

x_train = xy[0]
y_train = xy[1]

beta_gd = np.random.rand(1,)
bias = np.random.rand(1,)

learning_rate = 0.01

for i in range(1000) : 
    y_pred = beta_gd * x_train + bias
    
    error = sqrt(np.sum((y_train-y_pred)**2) / x_train.size)
    dW = - np.sum(x_train * (y_train - y_pred)) / x_train.size
    db = - np.sum((y_train - y_pred)) / x_train.size
    
    beta_gd -= learning_rate * dW
    bias -= learning_rate * db
    
    if i % 100 == 0:
        print('Epoch ({:10d}/1000) error: {:10f}, beta_gd: {:10f}, bias: {:10f}'.format(i, error, beta_gd.item(), bias.item()))





Epoch (         0/1000) error:  10.547483, beta_gd:   0.559616, bias:   0.715722
Epoch (       100/1000) error:   0.446367, beta_gd:   2.762753, bias:   1.015700
Epoch (       200/1000) error:   0.371854, beta_gd:   2.802357, bias:   0.846148
Epoch (       300/1000) error:   0.309781, beta_gd:   2.835350, bias:   0.704900
Epoch (       400/1000) error:   0.258069, beta_gd:   2.862835, bias:   0.587230
Epoch (       500/1000) error:   0.214989, beta_gd:   2.885732, bias:   0.489203
Epoch (       600/1000) error:   0.179101, beta_gd:   2.904807, bias:   0.407540
Epoch (       700/1000) error:   0.149203, beta_gd:   2.920698, bias:   0.339509
Epoch (       800/1000) error:   0.124297, beta_gd:   2.933936, bias:   0.282835
Epoch (       900/1000) error:   0.103548, beta_gd:   2.944964, bias:   0.235621
