Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준
- 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함

Numpy 특징
- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원함 (for문, list comprehension 없이)
- 선형대수와 관련된 다양한 기능을 제공함
- C, C++, 포트란 등의 언어와 통합 가능

import numpy as np

- numpy의 호출 방법
- 일반적으로 numpy는 np라는 alias(별칭) 이용해서 호출함
- 특별한 이유는 없음 세계적인 약속 같은 것

< Array creation >

test_array = np.array([1, 4, 5, 8], float) 
print(test_array)
type(test_array[3])

- numpy는 np.array 함수를 활용하여 배열을 생성함 -> ndarray
- numpy는 하나의 데이터 type만 배열에 넣을 수 있음
- List와 가장 큰 차이점, Dynamic typing not supported
- C의 Array를 사용하여 배열을 생성함

In [4]:
pip install numpy

You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
test_array = np.array(['1',2,'3',4,5],float)
print(test_array)
print(type(test_array[3]))  
# numpy.float64 : 하나의 데이터가 차지하는 공간이 64bit (메모리 공간의 수정)

[1. 2. 3. 4. 5.]
<class 'numpy.float64'>


< Array creation >

- shape : numpy array의 object의 dimension 구성을 반환함
    - Array (vector, matrix, tensor)의 크기, 형태 등에 대한 정보
    - (z축, y축, x축) 순서로 이루어짐 -> 일반적인 수학 직교좌표계의 x,y,z로 이해

- ndim – number of dimension (rank와 동치)
- size – data의 개수 (부피와 비슷)

- dtype : numpy array의 데이터 type을 반환함
    - Ndarray의 single element가 가지는 data type
    - 각 element가 차지하는 memory의 크기가 결정됨

In [6]:
test_array = np.array([1, 4, 5, "8"], float) # String Type의 데이터를 입력해도

print(test_array)
print(type(test_array[3])) # Float Type으로 자동 형변환을 실시
print(test_array.dtype) # Array(배열) 전체의 데이터 Type을 반환함 
print(test_array.shape) # Array(배열) 의 shape을 반환함


[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [7]:
test_array = np.array([[1,2,3],[4.5,5,6]],dtype=int)
test_array2 = np.array([[1,2,3],[4.5,5,6]],dtype=np.float32)
print(test_array)
print(test_array2)


[[1 2 3]
 [4 5 6]]
[[1.  2.  3. ]
 [4.5 5.  6. ]]


< reshape >

- Array의 shape의 크기를 변경함 (element의 갯수는 동일)
- Array의 size만 같다면 다차원으로 자유로이 변형가능
- reshape(z,y,x)꼴로 reshape가 되고, 
- -1은 size를 기반으로 나머지 setting된 숫자들을 기반으로 적절히 결정됨

< flatten >

- 다차원 array를 1차원 array로 변환

In [5]:
test_matrix = [[1,2,3,4],[5,6,7,8]]
print(np.array(test_matrix).shape)

new_array = np.array(test_matrix).reshape(4,2)
print(new_array)
new_array = np.array(test_matrix).reshape(-1,4)
print(new_array)
new_array = np.array(test_matrix).flatten()
print(new_array)


NameError: name 'np' is not defined

< indexing >

- List와 달리 이차원 배열에서 [0,0] 과 같은 표기법을 제공함
- Matrix 일경우 앞은 row 뒤는 column을 의미함

1) [z,y,x]와 같은 표기법 : 일반 데카르트 좌표계처럼 생각
2) [z][y][x] 와 같은 표기법 : 일반 데카르트 좌표계처럼 생각
-> 1,2번 둘다 거꾸로 읽기 <---- 방향으로!

< 2개만 있을 때 >
3) [x][y]와 같은 표기법 : 일반 컴퓨터 좌표계처럼 생각


In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
print(a)
print(a[0,0]) # Two dimensional array representation #1 
print(a[0][0]) # Two dimensional array representation #2

a[0,0] = 12 # Matrix 0,0 에 12 할당 print(a)
a[0][0] = 5 # Matrix 0,0 에 12 할당 print(a)
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[ 5 12  3]
 [ 4  5  6]]


< slicing >

- List와 달리 행과 열 부분을 나눠서 slicing이 가능함
- Matrix의 부분 집합을 추출할 때 유용함
- [ Row, Column ]순 : 컴퓨터식 좌표계로 범위 설정 (-y방향으로 row, +x 방향으로 column)
- [ Row ]순 : 입력받는 값이 하나만 있다면 Row를 의미, Column은 전체로 선택됨

In [26]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)

print(a[:,2:]) # 전체 Row의 2열 이상
print(a[1,1:3]) # 1 Row의 1열 ~ 2열
print(a[1:3]) # 1 Row ~ 2Row의 전체

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [36]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],int)

print(a[:,2:])
print(a[2:])
print(a[:,::2])
print(a[::3,::2])

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 1  3]
 [13 15]]


< arange >

- array의 범위를 지정하여, 값의 list를 생성하는 명령어
- list의 range와 같은 효과, integer로 0부터 29까지 배열추출
- floating point도 표시가능함

In [41]:
a = list(range(30))
print(a)
a = np.arange(30)
print(a)
a = np.arange(0,5,0.5)  # floating point도 표시가능함
print(a)
a = np.arange(30).reshape(5,6)
print(a)




[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


< ones, zeros and empty >

- zeros : 0으로 가득찬 ndarray 생성
- np.zeros(shape, dtype, order)

- ones : 1로 가득찬 ndarrary 생성
- np.ones(shape, dtype, order)

- empty : shape만 주어지고 비어있는 ndarray 생성 
- (memory initialization이 되지 않음)

 
- shape = (x) or (x,) : 인수가 1개일 경우 벡터로 생각
- shape = (y,x) : 인수가 2개일 경우 컴퓨터적 좌표계로 생각 (rank = 2)
- shape = (z,y,x): 인수가 3개일 경우 z, y, x 순서로 거꾸로 생각 (rank = 3)




In [66]:
a = np.zeros(shape=(10), dtype=np.int8)  # 10 - zero vector 생성
print(a)
a = np.zeros((2,5)) # 2 by 5 - zero matrix 생성
print(a)

a = np.ones(shape=(5,2))
print(a)
a = np.ones(shape=(2,5), dtype=np.int32)
print(a)

b = np.empty(shape=(10,),dtype=np.int8)
print(b)

c = np.empty(shape=(3,5))
print(c)



[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[1 1 1 1 1 1 1 1 1 1]
[[0.         0.         0.4472136  0.0531494  0.18257419]
 [0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]


< something_like >

- 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환


< identity >

- 단위 행렬(i 행렬)을 생성함


< eye >

- 대각선의 성분을 전부 1로 처리함
- 대각선인 1인 행렬, k값(시작하는 x좌표)의 시작 index의 변경이 가능


< diag >

- 대각 행렬의 값을 추출함
- k값(시작하는 x좌표)의 시작 index의 변경이 가능


< random sampling >

- 데이터 분포에 따른 sampling으로 array를 생성



In [80]:
test_matrix = np.arange(30).reshape(5,6)
print(np.ones_like(test_matrix))

test_matrix = np.identity(n=3, dtype=np.int8)
print(test_matrix)

np.identity(5,dtype =np.int8)

np.eye(5)
np.eye(N=3, M=5, dtype=np.int8)
np.eye(N=3, M=5, k=2, dtype=np.int8)

matrix = np.arange(30).reshape(5,6)
print(matrix)
np.diag(matrix, k =2)

np.random.uniform()



[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([ 2,  9, 16, 23])

< sum >

- ndarray의 element들 간의 합을 구함, list의 sum 기능과 동일

< axis >

- 모든 operation function을 실행할 때, 기준이 되는 dimension 축


In [1]:
test_array = np.arange(1,11)
print(test_array)
test_array.sum(dtype=np.float64)

test_array = np.arange(1,13).reshape(3,4)

print(test_array)
print(test_array.sum(axis=1))
print(test_array.sum(axis=0))


NameError: name 'np' is not defined